"""Добавил поле id_forked в shader

Revision ID: 237a310f062e
Revises: 7e798bbd7495
Create Date: 2025-04-26 23:22:49.901644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237a310f062e'
down_revision: Union[str, None] = '7e798bbd7495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaders', sa.Column('id_forked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaders', 'id_forked')
    # ### end Alembic commands ###
