"""Добавил поле hidden в комментарий

Revision ID: 49f543138138
Revises: 237a310f062e
Create Date: 2025-04-29 21:51:06.457569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f543138138'
down_revision: Union[str, None] = '237a310f062e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.execute("UPDATE comments SET hidden = FALSE")
    op.alter_column('comments', 'hidden', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'hidden')
    # ### end Alembic commands ###
