"""сделал avatar_url необязательным

Revision ID: 7e798bbd7495
Revises: 997eeb2f131a
Create Date: 2025-04-24 01:15:28.337887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e798bbd7495'
down_revision: Union[str, None] = '997eeb2f131a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
