"""Добавил поле background_url для пользователя

Revision ID: a23a1090b90f
Revises: 1b69ea1eb7cc
Create Date: 2025-05-04 15:40:43.092854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23a1090b90f'
down_revision: Union[str, None] = '1b69ea1eb7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('background_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'background_url')
    # ### end Alembic commands ###
